config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, controllers: { sessions: 'authors/sessions' }
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  resources :authors, only: %i[show], as: :author_profile
  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[create destroy]
  resources :suggestions, only: %i[index], as: :author_suggestions

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :suggestions, only: %i[create edit update destroy]
    member do
      get :submit
      put :submit
    end
  end

  authenticate :author, ->(user) { user.moderator? } do
    resources :moderators, only: %i[index show destroy] do
      member do
        get :publish_post
        put :publish_post
      end
    end
  end

  get '*path', to: 'application#routing_error'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  scope :not_reply, -> { where(parent_id: nil) }
  scope :all_reported, -> { joins(:reports).distinct }

  belongs_to :post
  belongs_to :author
  belongs_to :parent, class_name: 'Comment', optional: true
  has_one_attached :image
  has_many :comments, foreign_key: :parent_id, dependent: :destroy, inverse_of: :parent
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy

  validate :image_or_content
  validates :image, presence: true, unless: :content
  validates :content, presence: true, unless: :image

  private

  def image_or_content
    errors.add(:comment, 'text or image must be present') if image.blank? && content.blank?
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, :authorize_comment, only: %i[destroy]

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = t('comment_posted')
    else
      flash[:alert] = @comment.errors.full_messages.to_sentence
    end
    redirect_to post_path(params[:post_id])
  end

  def destroy
    flash[:alert] = if @comment.destroy
                      t('comment_deleted')
                    else
                      @comment.errors.full_messages.to_sentence
                    end
    if current_author.moderator?
      redirect_to root_path
    else
      redirect_to post_path(params[:post_id])
    end
  end

  private

  def comment_params
    params.permit(:author_id, :content, :image, :parent_id).merge(post_id: params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def authorize_comment
    authorize @comment
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def image_attached?(comment)
    comment.image.attached?
  end

  def comments?(comments)
    comments.any?
  end
end

app/views/comments/_comment.html.erb
<div class="card mt-3 rounded">
  <div class="card-header d-flex justify-content-between">
    <% if owner?(comment) %>
      <small>You</small>
    <%else%>
      <small>
        <strong><%= owner_name(comment) %></strong>
      </small>
    <% end %>
    <span>
      <small><%= created_time(comment)%> ago</small>
    </span>
  </div>
  <div class="card-body rounded-bottom">
    <div class="mb-3">
      <%= comment.content%>
    </div>
    <% if image_attached?(comment) %>
      <div class="mb-3">
        <%= cl_image_tag(comment.image.key, width: '20%', height: '20%')%>
      </div>
    <% end %>
    <div class="mb-1 d-flex justify-content-between text-center btn-sm">
      <span class="d-flex">
        <small class="mr-2 mt-auto">
          <%= render 'likes/button', likeable: comment %>
        </small>
        <% if !reply?(comment) %>
          <small class="comment-form-display mr-2 btn btn-primary mt-auto btn-sm">
            <a href="#" class="text-decoration-none text-white">Reply</a>
          </small>
          <div class="comment-form">
            <%= render partial: 'comments/form', locals: {post: comment.post, parent: comment} %>
          </div>
        <% end %>
      </span>
      <span>
        <% if owner_or_moderator?(comment) %>
          <%= button_to "Delete", post_comment_path(comment.post_id, comment), method: :delete, class:"btn btn-danger btn-sm" %>
        <% end %>
        <%= render 'reports/button', reportable: comment %>
        <span>
        </div>
        <div class="ml-2">
          <span class="d-flex">
            <small class="mr-2 text-center" >
              <%= pluralize(likes_count(comment), "Like")%>
            </small>
            <% if !reply?(comment) %>
              <small>
                <%= pluralize(reply_count(comment), "Reply")%>
              </small>
            <% end %>
          </span>
          <span></span>
        </div>
        <div class="pl-4">
          <%replies = replies_of(comment)%>
          <%= render replies %>
        </div>
      </div>
    </div>

app/views/comments/_form.html.erb
<%= form_with url: post_comments_path(post), method: :post do |form| %>
  <% if !parent.nil? %>
    <%= form.hidden_field :parent_id, value: "#{parent.id}"  %>
  <% end %>
  <%= form.hidden_field :author_id, value: "#{current_author.id}"  %>
  <div class= 'form-group'>
    <%= form.label :comment%>
    <%= form.text_area :content, class:"form-control mb-2 bg-transparent text-white", placeholder:"Type here..."%>
  </div>
  <div class= 'form-group'>
    <%= form.file_field :image, accept: 'image/jpeg, image/png, image/jpg, image/webp'%>
  </div>
  <div>
    <%= form.submit "Submit", class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>