config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, controllers: { sessions: 'authors/sessions' }
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  resources :authors, only: %i[show], as: :author_profile
  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[create destroy]
  resources :suggestions, only: %i[index], as: :author_suggestions

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :suggestions, only: %i[create edit update destroy]
    member do
      get :submit
      put :submit
    end
  end

  authenticate :author, ->(user) { user.moderator? } do
    resources :moderators, only: %i[index show destroy] do
      member do
        get :publish_post
        put :publish_post
      end
    end
  end

  get '*path', to: 'application#routing_error'
end

app/views/shared/_alerts.html.erb
<span class="success_msgs"> <% if notice %>
    <p class="alert alert-success">
      <%= notice %>
    </p>
 <% end %> </span>
<span class="error_msgs"> <% if alert %>
    <p class="alert alert-danger">
      <%= alert %>
    </p>
 <% end %> </span>

app/views/shared/_blogs.html.erb
<div class="row">
  <% posts.each do |post| %>
    <div class="col-md6 col-lg-4">
      <div class="card mb-4">
        <div class="rounded-top" style="width: 100%; height: 250px; background-size: cover; background-position: center;">
          <%= cl_image_tag(post.header_image.key, width: '100%', height: '100%')%>
        </div>
        <div class="card-body rounded-bottom pt-2 d-flex flex-column">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"> <%= truncate(post.description, length: 200) %></p>
          <div class="d-flex justify-content-between">
            <small class="mb-3">
              <%= time_ago_in_words(post.published_at) %> ago
            </small>
          </div>
          <%= link_to "Read Blog", post_path(post), class: "btn btn-primary mt-auto" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_comment_suggestion_tab.html.erb
<div class="comment-suggestion-tab container">
  <ul class="nav nav-tabs mt-2 mb-2 border-0">
    <li class="nav-item">
      <a class="nav-link active btn-primary rounded mr-2" data-bs-toggle="tab" href="#comment"><strong> <%= pluralize(post.comments.count, "Comment")%></strong></a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn-primary rounded" data-bs-toggle="tab" href="#suggestion"><strong> <%= pluralize(post.suggestions.where(parent_id: nil).count, "Suggestion")%></strong></a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="comment">
      <div class="row rounded">
        <div class="col">
          <div class="card-body rounded">
            <%= render post.comments.not_reply.order(id: :desc) %>
            <div class="mt-3 mb-3">
              <%= render partial: 'comments/form', locals: {post: post, parent: nil} %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane" id="suggestion">
      <div class="row g-0 rounded shadow-sm">
        <div class="col">
          <div class="card-body rounded">
            <%= render 'shared/suggestion', post: post %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"
      ></script>
</div>

app/views/shared/_comments_list.html.erb
<% comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/shared/_empty.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-md-4 col-sm-6">
    <div class="card border-0">
      <div class="card-header">
        <h6 class="card-title mb-0 text-center">
          No Posts
        </h6>
      </div>
      <div class="card-body text-center">
        <%= link_to  "Create a post", new_post_path, class:'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
  <% if model.errors.any? %>
    <div style="color: red">
      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark container-fluid">
  <span class="pb-5">
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Infinity <strong>Blog</strong></a>
  </span>
  <span class="ml-auto">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if current_author.moderator? %>
          <li class="">
            <%= button_to "Sign Out", destroy_author_session_path, method: :delete, form: {  data: { turbo: :false } }, class: "btn btn-danger mb-3" %>
          </li>
        <% else %>
          <li class="<%= active_class(root_path) %>">
            <%= link_to  "Home", root_path, class:"nav-link" %>
          </li>
          <li class="<%= active_class(author_profile_path(current_author)) %>">
            <%= link_to  "Profile", author_profile_path(current_author),class:"nav-link" %>
          </li>
          <li class="<%= active_class(author_suggestions_path) %>">
            <%= link_to  "My Suggestions", author_suggestions_path,class:"nav-link" %>
          </li>
          <li class="<%= active_class(new_post_path) %>">
            <%= link_to  "New Post", new_post_path, class:"nav-link mr-4" %>
          </li>
          <li class="">
            <%= button_to "Sign Out", destroy_author_session_path, method: :delete, form: {  data: { turbo: :false } }, class: "btn btn-danger mb-3" %>
          </li>
        <% end %>
      </ul>
    </div>
    <small class="d-flex text-white justify-content-between mb-2">
      <span></span>
      <span class="d-flex text-secondary ">
        signed in as <%= current_author.first_name%> <%= current_author.last_name%>
      </span>
    </small>
  </span>
</nav>

app/views/shared/_post.html.erb
<div class="card mb-5">
  <div class="card-body rounded">
    <div class="card border">
      <div class="rounded-top" style="width: 100%; height:550px; background-size: cover; background-position: center;">
        <%= cl_image_tag(post.header_image.key, width: '100%', height: '100%')%>
      </div>
    </div>
    <div class="card-header">
      <h1 class="card-title"><%= post.title%></h1>
    </div>
    <div class="card-header">
      <div class="d-flex justify-content-between">
        <small>
          By <strong><%= post.author.first_name %> <%= post.author.last_name %></strong>
        </small>
        <small>
          <strong class="text-danger"><%= post.reports.count %> Reports</strong>
        </small>
      </div>
    </div>
    <div class="card-header rounded-bottom text-center">
      <small class="d-flex justify-content-between">
        <span>
        </span>
      </small>
    </div>
    <div class="mb-3 p-3">
      <div class="">
        <%= post.content%>
      </div>
    </div>
  </div>
</div>

app/views/shared/_suggestion.html.erb
 <% if post.suggestions.present? %>
  <div class="mt-3 mb-3">
    <%= render post.suggestions.where(parent_id: nil).includes(:author).order(id: :desc) %>
  </div>
<%else%>
  <h4 class="mt-3 mb-3 text-center">
    No Suggestions
  </h4>
<% end %>
<% if current_author.id != post.author_id  %>
  <div class="mt-3 mb-3">
    <%= render partial: 'suggestions/form', locals: {post: post, parent: nil} %>
  </div>
<% end %>

app/views/shared/_suggestions.html.erb
 <% if post.suggestions.present? %>
  <div class="mt-3 mb-3">
    <%= render post.suggestions.where(parent_id: nil).includes(:author).order(id: :desc) %>
  </div>
<%else%>
  <h4 class="mt-3 mb-3 text-center">
    No Suggestions
  </h4>
<% end %>
<% if current_author.id != post.author_id  %>
  <div class="mt-3 mb-3">
    <%= render partial: 'readers/suggestions/form', locals: {post: post, parent: nil} %>
  </div>
<% end %>