config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, controllers: { sessions: 'authors/sessions' }
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  resources :authors, only: %i[show], as: :author_profile
  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[create destroy]
  resources :suggestions, only: %i[index], as: :author_suggestions

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :suggestions, only: %i[create edit update destroy]
    member do
      get :submit
      put :submit
    end
  end

  authenticate :author, ->(user) { user.moderator? } do
    resources :moderators, only: %i[index show destroy] do
      member do
        get :publish_post
        put :publish_post
      end
    end
  end

  get '*path', to: 'application#routing_error'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  scope :all_reported, -> { joins(:reports).distinct }

  enum :status, { unpublished: 0, pending: 1, published: 2 }, default: 0

  belongs_to :author
  has_rich_text :content
  has_one_attached :header_image
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  has_many :suggestions, dependent: :destroy

  validates :title, :description, :header_image, presence: true
  validates :title, length: { within: 5..100 }
  validates :description, length: { within: 5..200 }
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PostsController < ApplicationController
      def index
        @posts = Post.all.order(id: :desc)
        render json: @posts, root: false
      end

      def show
        @post = Post.find(params[:id])
        render json: @post, root: false
      end
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, :authorize_post, only: %i[update destroy submit]

  def index
    @posts = current_author.posts.order(id: :desc)
    redirect_to root_path
  end

  def show
    if Post.find(params[:id]).published?
      @post = Post.find(params[:id])
    else
      redirect_to root_path, notice: t('post_unpublished')
    end
  end

  def new
    @post = current_author.posts.build
  end

  def create
    @post = current_author.posts.new(post_params)
    if @post.save
      redirect_to edit_post_path(@post), notice: t('post_created')
    else
      render :new
    end
  end

  def edit
    @post = current_author.posts.find(params[:id])
  end

  def update
    if @post.update(post_params)
      redirect_to edit_post_path(@post), notice: t('post_updated')
    else
      render :edit
      flash.now[:alert] = t('invalid_values')
    end
  end

  def submit
    if @post.pending?
      @post.unpublished!
      @post.update(published_at: nil)
      flash[:alert] = t('submission_cancelled')
    else
      @post.pending!
      flash[:notice] = t('post_submitted')
    end
    redirect_to edit_post_path(@post)
  end

  def destroy
    redirect_to author_profile_path(current_author), alert: t('post_deleted') if @post.destroy
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_post
    authorize @post
  end

  def post_params
    params.require(:post).permit(:title, :description, :content, :header_image, :status)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def published_time(post)
    time_ago_in_words(post.published_at)
  end

  def content?(post)
    post.content.present?
  end

  def posts?(posts)
    posts.present?
  end

  def post_unpublished?(post)
    post.unpublished?
  end
end

app/views/posts/_empty.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-md-4 col-sm-6">
    <div class="card border-0">
      <div class="card-header">
        <h6 class="card-title mb-0 text-center">
          No Posts
        </h6>
      </div>
      <div class="card-body text-center">
        <%= link_to  "Create a post", new_post_path, class:'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= render 'shared/errors', model: post  %>
  <div class= 'form-group'>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class= 'form-group'>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: 'form-control'%>
  </div>
  <div class= 'form-group'>
    <%= form.label :header_image, style: "display: block" %>
    <%= form.file_field :header_image, accept: 'image/jpeg, image/png, image/jpg, image/webp'%>
    <div class="mt-1">
      <% if post.header_image.present? %>
        <small>Selected Image</small>
        <%= cl_image_tag(post.header_image.key, width: '100%')%>
      <%end%>
    </div>
  </div>
  <div>
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class=" text-white mb-3">
  Posts
</div>
<% posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
    <div class="card mb-3 border">
      <div class="card-body rounded">
        <div class="row">
          <div class="col-md-2">
            <% if post.header_image.present? %>
              <div class="rounded">
                <%= cl_image_tag(post.header_image.key, width: '100%', height: '100%')%>
              </div>
            <%end%>
          </div>
          <div class="col-md-10">
            <% if post.published? %>
              <span class="badge badge-success mb-3"> Published</span>
            <%elsif post.pending?%>
              <span class="badge badge-primary mb-3"> Pending</span>
            <%else%>
              <span class="badge badge-secondary mb-3"> Unpublished</span>
            <%end%>
            <% if post.published? %>
              <small class="text-white">
                <%= published_time(post) %> ago
              </small>
            <%end%>
            <h5 class="card-title mb-2 text-white"><%= post.title%></h5>
            <p class="text-secondary"><%= post.description%></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to "Back", root_path, class:"btn btn-secondary mb-3"%>
    <div class="card border">
      <div class="card-header">
        Editing Post
      </div>
      <div class="card-body">
        <%= render "form", post: @post %>
      </div>
      <div class="card-footer">
        <%= button_to "Delete", post_path(@post), class: "btn btn-danger btn-block", method: :delete %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="d-flex text-white justify-content-between">
      <% if @post.published? %>
        <div class="mb-4"> Post is live </div>
      <%elsif @post.pending? %>
        <%= link_to "Cancel Submission", submit_post_path(@post), method: :put, data: { confirm: 'Are you sure?' }, class:"btn btn-secondary mb-3"%>
      <%else%>
        <% if content?(@post) %>
          <%= link_to "Submit", submit_post_path(@post), method: :put, class:"btn btn-primary mb-3"%>
        <%else%>
          <p>Add some content to publish</p>
        <% end %>
      <%end%>
    </div>
    <div class="card mb-5 border">
      <div class="card-header text-right">
        <% if @post.published? %>
          <b>Published</b> <%= published_time(@post) %> ago
        <%else%>
          Not published yet
        <%end%>
      </div>
      <div class="card-body pt-5">
        <div class="mb-3 p-3">
          <div class="post-form">
            <%= form_with model: @post do |form| %>
              <div class="field">
                <%= form.rich_text_area :content %>
              </div>
              <div class="mt-3">
                <%= form.submit "Save", class:"btn btn-primary" %>
                <a href='#' class="cancel btn btn-secondary">Cancel</a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to "Back to posts", author_profile_path(current_author), class: "btn btn-dark mb-3" %>
    <div class="card border-0">
      <div class="card-header">
          <h6 class="card-title mb-0">New post</h6>
      </div>
      <div class="card-body">
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card mb-5">
  <div class="card-body rounded">
    <div class="card border-0">
      <div class="rounded-top" style="width: 100%; height:550px; background-size: cover; background-position: center;">
        <%= cl_image_tag(@post.header_image.key, width: '100%', height: '100%')%>
      </div>
    </div>
    <div class="card-header">
      <h1 class="card-title"><%= @post.title%></h1>
    </div>
    <div class="card-header">
      <div class="d-flex justify-content-between">
        <small>
          By <strong><%= @post.author.first_name %> <%= @post.author.last_name %></strong>
        </small>
        <% if @post.published? %>
          <small>
            <b>Published</b> <%= published_time(@post) %> ago
          </small>
        <%else%>
          <small>Not published yet</small>
        <%end%>
      </div>
    </div>
    <div class="card-header rounded-bottom text-center">
      <small class="d-flex justify-content-between">
        <div id="like-btn-<%= @post.id%>" >
          <%= render 'likes/button', likeable: @post %>
        </div>
        <span class="text-danger">
          <% if @post.author == current_author %>
            <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary btn-small text-decoration-none' %>
          <% end %>
          <%= render 'reports/button', reportable: @post %>
        </span>
      </small>
    </div>
    <div class="mb-3 p-3">
      <div class="">
        <%= @post.content%>
      </div>
    </div>
  </div>
</div>
<div class="card mb-3">
  <%= render 'shared/comment_suggestion_tab', post: @post %>
</div>