config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :authors, controllers: { sessions: 'authors/sessions' }
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index show]
    end
  end

  resources :authors, only: %i[show], as: :author_profile
  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[create destroy]
  resources :suggestions, only: %i[index], as: :author_suggestions

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :suggestions, only: %i[create edit update destroy]
    member do
      get :submit
      put :submit
    end
  end

  authenticate :author, ->(user) { user.moderator? } do
    resources :moderators, only: %i[index show destroy] do
      member do
        get :publish_post
        put :publish_post
      end
    end
  end

  get '*path', to: 'application#routing_error'
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :author
  belongs_to :reportable, polymorphic: true

  validates :author_id, uniqueness: { scope: %i[reportable_id reportable_type] }
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  def create
    @report = Report.new(report_params)
    if @report.save
      flash[:notice] = t('report_submitted')
    else
      flash[:alert] = @report.errors.full_messages.to_sentence
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @report = Report.find(params[:id])

    flash[:alert] = if @report.destroy
                      t('report_cancelled')
                    else
                      @report.errors.full_messages.to_sentence
                    end
    redirect_back(fallback_location: root_path)
  end

  private

  def report_params
    params.permit(:author_id, :reportable_id, :reportable_type)
  end
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
  def current_report(reportable)
    Report.find_by(reportable: reportable)
  end

  def report_count(reportable)
    reportable.reports.count
  end

  def delete_post_reports(post_id)
    Post.find(post_id).reports.destroy_all
  end
end

app/views/reports/_button.html.erb
<% if !owner_or_moderator?(reportable) %>
  <% report = current_report(reportable) %>
  <% if report.nil? %>
    <%= button_to "Report", reports_path(author_id: current_author.id, reportable_id: reportable.id, reportable_type: reportable.class.to_s), method: :post, class:"btn btn-warning btn-sm" %>
  <%else%>
    <%= button_to "Cancel Report", report_path(report), method: :delete, remote: true, class:"btn btn-secondary btn-sm" %>
  <% end %>
<% else %>
  <small class="text-warning">
    <%= pluralize(report_count(reportable), "report")%>
  </small>
<% end %>